services:
#  php-fpm-8.3:
#    build:
#      context: .
#      dockerfile: DockerFiles/php/8.2/Dockerfile
#    container_name: php-fpm-8.3
#    user: "${UID}:${GID}"
#    volumes:
#      - ./code:/var/www/exam-creator
#    networks:
#      - exam_network

  php-fpm:
    build:
      context: .
      dockerfile: DockerFiles/php/${PHP_VERSION}/Dockerfile
      args:
        UID: "${UID}"
        GID: "${GID}"
    extra_hosts:
      - host.docker.internal:host-gateway
    container_name: php-fpm-${PHP_VERSION}
    ports:
      - "55690:9003"
    volumes:
      - ./code:/var/www/exam-creator
    networks:
      - exam_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./code:/var/www/exam-creator
      - nginx_cache:/var/cache/nginx
    depends_on:
      - php-fpm
    networks:
      - exam_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - exam_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - exam_network

  composer:
    image: composer:latest
    container_name: composer
    user: "${UID}:${GID}"
    volumes:
      - ./code:/app
    working_dir: /app
    networks:
      - exam_network
    entrypoint: ["composer"]
    command: ["--version"]

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - exam_network

volumes:
  postgres_data:
  nginx_cache:

networks:
  exam_network:
    driver: bridge
